name: stagexl_isometric
version: 0.1.1
author: Bernhard Pichler <support@stagexl.org>
description: An isometric graphics extension for StageXL.
homepage: https://github.com/bp74/StageXL_Isometric

environment:
  sdk: '>=1.20.0 <2.0.0'

dependencies:
  browser: any
  stagexl: '^1.0.0'

transformers:
- $dart2js:
    commandLineOptions: ["--trust-type-annotations", "--trust-primitives"]
    minify: true
