name: stagexl_isometric
version: 0.2.0
author: Bernhard Pichler <support@stagexl.org>
description: An isometric graphics extension for StageXL.
homepage: https://github.com/bp74/StageXL_Isometric

environment:
  sdk: '>=2.0.0-dev.64 <3.0.0'

dependencies:
  stagexl: '>=1.4.0 <2.0.0'

dev_dependencies:
  build_runner: '>=0.10.0 <1.0.0'
  build_test: '>=0.10.2+5 <1.0.0'
  build_web_compilers: '>=0.4.0+4 <1.0.0'