name: StageXL_Isometric
version: 0.1.0
author: Bernhard Pichler <support@stagexl.org>
description: An isometric graphics extension for StageXL.
homepage: http://www.stagexl.org
dependencies:
  browser: any
  meta: any
  stagexl: any
